site_name: Libre Office Writer

theme:
  name: material
  language: pt-BR
  favicon: https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/LibreOffice_6.1_Writer_Icon.svg/2048px-LibreOffice_6.1_Writer_Icon.svg.png
  logo: https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/LibreOffice_6.1_Writer_Icon.svg/2048px-LibreOffice_6.1_Writer_Icon.svg.png
  palette:
    # accent: blue
  
    - scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
    - Home: index.md
    - Atas:
      - 14/09/2023: atas/ata_14_09.md
      - 26/09/2023: atas/ata_26_09.md
    - Apresentações:
      - Apresentação 1: apresentacoes/apresentacao1.md
    - Planejamento: 
      - Aplicativo Escolhido: planejamento/appEscolhido.md
      - Ferramentas: planejamento/ferramentas.md
      - Cronograma: planejamento/cronograma.md
      - Disponibilidade dos membros: planejamento/heatmap.md
      - Metodologias: planejamento/metodologias.md
    - Elicitação:
      - Técnicas:
        - Brainstorming: elicitacao/tecnicas/brainstorming.md

