site_name: Libre Office Writer

theme:
  name: material
  language: pt-BR
  favicon: https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/LibreOffice_6.1_Writer_Icon.svg/2048px-LibreOffice_6.1_Writer_Icon.svg.png
  logo: https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/LibreOffice_6.1_Writer_Icon.svg/2048px-LibreOffice_6.1_Writer_Icon.svg.png
  palette:
    # accent: blue
  
    - scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
    - Home: index.md
    - Atas:
      - 14/09/2023: atas/ata_14_09.md
      - 26/09/2023: atas/ata_26_09.md
      - 16/10/2023: atas/ata_16_10.md
    - Apresentações:
      - Apresentação 1: apresentacoes/apresentacao1.md
      - Apresentação 2: apresentacoes/apresentacao2.md
      - Apresentação 3: apresentacoes/apresentacao3.md
      - Apresentação 4: apresentacoes/apresentacao4.md
    - Planejamento: 
      - Aplicativo Escolhido: planejamento/appEscolhido.md
      - Ferramentas: planejamento/ferramentas.md
      - Cronograma: planejamento/cronograma.md
      - Disponibilidade dos membros: planejamento/heatmap.md
      - Metodologias: planejamento/metodologias.md
    - Elicitação: 
      - Perfil do usuário: elicitacao/perfilUsuario.md
      - Técnicas:
        - Introspecção: elicitacao/introspeccao.md
        - Questionário: elicitacao/questionario.md
        - Brainstorming: elicitacao/tecnicas/brainstorming.md
      - Priorização:
        - $100: elicitacao/100dolares.md
        - Moscow: elicitacao/priorizacao/moscow.md
    - Modelagem:
      - Casos de Uso: modelagem/casosDeUso.md
      - Especificação Suplementar: modelagem/especificacaoSuplementar.md
      - Cenários: modelagem/cenarios.md
      - Léxicos: modelagem/lexicos.md
      - Ágil:
        - NFR Framework: modelagem/agil/nfr.md
        - Backlog: modelagem/agil/backlog.md
        - Histórias de Usuário: modelagem/agil/historiasDeUsuario.md
    - Verificação:
      - Grupo 1:
          - Metodologia: verificacao/grupo1/metodologia.md
          - Elicitação:
            - Perfil de usuário: verificacao/grupo1/elicitacao/perfilDeUsuario.md

