site_name: Libre Office Writer

theme:
  name: material
  language: pt-BR
  favicon: https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/LibreOffice_6.1_Writer_Icon.svg/2048px-LibreOffice_6.1_Writer_Icon.svg.png
  logo: https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/LibreOffice_6.1_Writer_Icon.svg/2048px-LibreOffice_6.1_Writer_Icon.svg.png
  palette:
    # accent: blue
  
    - scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Planejamento: 
      - Ferramentas: planejamento/ferramentas.md
      - Disponibilidade dos membros: planejamento/heatmap.md
  - Atas:
      - 14/09/2023: atas/ata_14_09.md


